language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --system --deploy --ignore-pipfile --dev
  - pipenv run pip install -e .
script: py.test -v --cov=./ --cov-report term-missing -v
after_success:
  - codecov
